# Generated by Django 4.1.7 on 2023-06-26 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_remove_hydjobs_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delhijobs',
            name='date',
        ),
        migrations.RemoveField(
            model_name='punejobs',
            name='date',
        ),
    ]
